{"stack":"NotFoundError: Can't find any order report\n    at Object.exports.getOrderReport (/api/services/report.service.js:63:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /api/controllers/report.controller.js:6:17","level":"error","message":"Can't find any order report","timestamp":"2021-09-12T00:31:54.456Z"}
{"stack":"NotFoundError: Can't find any product\n    at Object.exports.getProducts (/api/services/product.service.js:108:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /api/controllers/product.controller.js:82:14","level":"error","message":"Can't find any product","timestamp":"2021-09-12T01:27:20.943Z"}
{"stack":"NotFoundError: Can't find any order report\n    at Object.exports.getOrderReport (/api/services/report.service.js:63:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /api/controllers/report.controller.js:6:17","level":"error","message":"Can't find any order report","timestamp":"2021-09-12T03:18:49.880Z"}
{"stack":"NotFoundError: Not Found\n    at /api/app.js:42:8\n    at Layer.handle [as handle_request] (/api/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/api/node_modules/express/lib/router/index.js:317:13)\n    at /api/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/api/node_modules/express/lib/router/index.js:335:12)\n    at next (/api/node_modules/express/lib/router/index.js:275:10)\n    at /api/node_modules/express/lib/router/index.js:635:15\n    at next (/api/node_modules/express/lib/router/index.js:260:14)\n    at /api/node_modules/express/lib/router/index.js:635:15\n    at next (/api/node_modules/express/lib/router/index.js:260:14)","level":"error","message":"Not Found","timestamp":"2021-09-12T04:00:49.090Z"}
{"stack":"NotFoundError: Not Found\n    at /api/app.js:42:8\n    at Layer.handle [as handle_request] (/api/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/api/node_modules/express/lib/router/index.js:317:13)\n    at /api/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/api/node_modules/express/lib/router/index.js:335:12)\n    at next (/api/node_modules/express/lib/router/index.js:275:10)\n    at /api/node_modules/express/lib/router/index.js:635:15\n    at next (/api/node_modules/express/lib/router/index.js:260:14)\n    at /api/node_modules/express/lib/router/index.js:635:15\n    at next (/api/node_modules/express/lib/router/index.js:260:14)","level":"error","message":"Not Found","timestamp":"2021-09-12T04:00:56.334Z"}
{"stack":"UnauthorizedError: You must login to get access\n    at /api/controllers/user.controller.js:65:9\n    at asyncUtilWrap (/api/node_modules/express-async-handler/index.js:3:20)\n    at Layer.handle [as handle_request] (/api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/api/node_modules/express/lib/router/layer.js:95:5)\n    at /api/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/api/node_modules/express/lib/router/index.js:335:12)\n    at next (/api/node_modules/express/lib/router/index.js:275:10)\n    at Function.handle (/api/node_modules/express/lib/router/index.js:174:3)","level":"error","message":"You must login to get access","timestamp":"2021-09-12T04:22:18.542Z"}
{"stack":"ConflictError: Username already exists\n    at Object.exports.signup (/api/services/user.service.js:80:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /api/controllers/user.controller.js:17:17","level":"error","message":"Username already exists","timestamp":"2021-09-12T04:26:43.398Z"}
{"stack":"InternalServerError: Validation error\n    at Object.exports.signup (/api/services/user.service.js:80:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /api/controllers/user.controller.js:17:17","level":"error","message":"Validation error","timestamp":"2021-09-12T04:26:54.370Z"}
{"stack":"InternalServerError: Validation error\n    at Object.exports.signup (/api/services/user.service.js:80:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /api/controllers/user.controller.js:17:17","level":"error","message":"Validation error","timestamp":"2021-09-12T04:27:28.240Z"}
{"level":"error","message":"Validation Failed","timestamp":"2021-09-12T04:28:31.851Z"}
{"stack":"InternalServerError: Validation error\n    at Object.exports.signup (/api/services/user.service.js:80:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /api/controllers/user.controller.js:17:17","level":"error","message":"Validation error","timestamp":"2021-09-12T04:29:35.489Z"}
{"stack":"ConflictError: Username already exists\n    at Object.exports.signup (/api/services/user.service.js:80:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /api/controllers/user.controller.js:17:17","level":"error","message":"Username already exists","timestamp":"2021-09-12T04:29:46.008Z"}
{"stack":"InternalServerError: Validation error\n    at Object.exports.signup (/api/services/user.service.js:80:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /api/controllers/user.controller.js:17:17","level":"error","message":"Validation error","timestamp":"2021-09-12T04:29:57.498Z"}
{"stack":"ConflictError: Username already exists\n    at Object.exports.signup (/api/services/user.service.js:88:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /api/controllers/user.controller.js:17:17","level":"error","message":"Username already exists","timestamp":"2021-09-12T04:33:30.369Z"}
{"stack":"ConflictError: Username already exists\n    at Object.exports.signup (/api/services/user.service.js:88:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /api/controllers/user.controller.js:17:17","level":"error","message":"Username already exists","timestamp":"2021-09-12T04:34:56.694Z"}
{"stack":"ConflictError: Email already exists\n    at Object.exports.signup (/api/services/user.service.js:88:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /api/controllers/user.controller.js:17:17","level":"error","message":"Email already exists","timestamp":"2021-09-12T04:35:21.505Z"}
